name: Bug report
description: Create a report to help us improve


body:
- type: textarea
  id: summary
  attributes:
    label: Bug summary
    description: "A clear and concise description of what the bug is."
  validations:
    required: true
- type: checkboxes
  id: operating-systems
  attributes:
    label: Which operating systems have you used?
    description: You may select more than one.
    options:
    - label: Linux
    - label: macOS
    - label: Windows
- type: textarea
  id: repro
  attributes:
    label: Reproduction steps
    description: "Example of how you trigger this bug. Please walk us through it step by step."
    value: |
      # 1. Given the following command(s)
      ...
    render: bash
  validations:
    required: true
- type: textarea
  id: expected
  attributes:
    label: Expected behaviour
    description: "What you expected to happen."
  validations:
    required: true
- type: textarea
  id: additional
  attributes:
    label: Additional Context
    description: "Any additional information or dependencies that can help diagnose the problem."
  validations:
    required: false
