name: Tests

on:
  - push
  - pull_request

env:
  VIRA_USER: ${{ secrets.VIRA_USER }}
  VIRA_USER_PASSWORD: ${{ secrets.VIRA_USER_PASSWORD }}
  VIRA_ACCESS_TOKEN: ${{ secrets.VIRA_ACCESS_TOKEN }}
  VIRA_TEST_USER: ${{ secrets.VIRA_TEST_USER }}
  VIRA_TEST_USER_PASSWORD: ${{ secrets.VIRA_TEST_USER_PASSWORD }}
  VIRA_TEST_ACCESS_TOKEN: ${{ secrets.VIRA_TEST_ACCESS_TOKEN }}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.11']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox tox-gh-actions
    - name: Test with tox
      run: tox
